cmd c "New directory and file" local peer test
Running recursive check for <TESTBASE>/test ...
Checking recursive for modified files <TESTBASE>/test 
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local' '-'.
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local/usr' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local/usr' '-'.
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local/usr/local' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local/usr/local' '-'.
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local/usr/local/sbin' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local/usr/local/sbin' '-'.
mark other operation: 'NEW' 'peer:<TESTBASE>/test/local/usr/local/sbin/hej' '-'.
mark other operation: 'NEW' 'other:<TESTBASE>/test/local/usr/local/sbin/hej' '-'.
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local/usr/local/def' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local/usr/local/def' '-'.
mark other operation: 'NEW' 'peer:<TESTBASE>/test/local/usr/local/def/hej' '../sbin/hej'.
mark other operation: 'NEW' 'other:<TESTBASE>/test/local/usr/local/def/hej' '../sbin/hej'.
mark other operation: 'MKDIR' 'peer:<TESTBASE>/test/local/usr/local/abc' '-'.
mark other operation: 'MKDIR' 'other:<TESTBASE>/test/local/usr/local/abc' '-'.
Checking for deleted files <TESTBASE>/test recursive.
