a/1/ignored~
a/1/d/ignored.o
a/1/e/ignored.o
a/1/f/ignored.o
a/2/ignored~
a/2/d/ignored.o
a/2/e/ignored.o
a/2/f/ignored.o
a/3/ignored~
a/3/d/ignored.o
a/3/e/ignored.o
a/3/f/ignored.o
b/1/ignored~
b/1/d/ignored.o
b/1/e/ignored.o
b/1/f/ignored.o
b/2/ignored~
b/2/d/ignored.o
b/2/e/ignored.o
b/2/f/ignored.o
b/3/ignored~
b/3/d/ignored.o
b/3/e/ignored.o
b/3/f/ignored.o
c/1/ignored~
c/1/d/ignored.o
c/1/e/ignored.o
c/1/f/ignored.o
c/2/ignored~
c/2/d/ignored.o
c/2/e/ignored.o
c/2/f/ignored.o
c/3/ignored~
c/3/d/ignored.o
c/3/e/ignored.o
c/3/f/ignored.o

