| peer     | <TESTBASE>/test/local              | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a            | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/1/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/2/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/3/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/a/f1.txt     | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b            | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/1/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/2/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/3/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/b/f1.txt     | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c            | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/1/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/2/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3          | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/d        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/d/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/e        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/e/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/f        | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/f/f1.txt | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/3/f1.txt   | RM        | NULL  |   64 |
| peer     | <TESTBASE>/test/local/c/f1.txt     | RM        | NULL  |   64 |
