#!/bin/bash

verbose=0

if [ "$1" = "-v" ]; then
	verbose=1
	shift
fi

if [ $# != 3 ]; then
	echo "Usage: $0 [-v] host1[@host1] host2[@host2] basedir" >&2
	exit 1
fi

left1="${1%@*}"
left2="${1#*@}"
if [ "$left2" != "-" ] ; then
    LEFT_HOST="-P $left2"
fi
right1="${2%@*}"
right2="${2#*@}"
if [ "$right2" != "-" ] ; then
    RIGHT_HOST="-P $right2"
fi

basedir="$3"

left_cmd="ssh  $left1  'csync2 -or $basedir $RIGHT_HOST '"
right_cmd="ssh $right1 'csync2 -or $basedir $LEFT_HOST  '"

if [ $verbose -eq 1 ]; then
	echo
	echo "L: $left_cmd"
	echo "R: $right_cmd"
	echo
fi

diff <( eval "$left_cmd" ) <( eval "$right_cmd" ) 

if [ $verbose -eq 1 ]; then
	echo
	echo "X - ... Found this file on left host ($1) only."
	echo "- X ... Found this file on right host ($2) only."
	echo "X X ... Found file on both hosts but content is different."
	echo
fi

